SELECT 
	USERS.BATCH_UID
	,USERS.USER_ID
	,USERS.FIRSTNAME
	,USERS.LASTNAME
	,CM.BATCH_UID COURSE_BATCH_UID
	,CM.COURSE_ID
	,ACTIVITY_ACCUMULATOR.DATA
	,ACTIVITY_ACCUMULATOR.INTERNAL_HANDLE
	,ACTIVITY_ACCUMULATOR.TIMESTAMP
FROM bblearn.ACTIVITY_ACCUMULATOR
INNER JOIN bblearn.USERS
ON ACTIVITY_ACCUMULATOR.USER_PK1=USERS.PK1
OUTER JOIN bblearn.COURSE_MAIN CM
ON ACTIVITY_ACCUMULATOR.COURSE_PK1 = CM.PK1
--WHERE ACTIVITY_ACCUMULATOR.[TIMESTAMP] > @FromDate
WHERE ACTIVITY_ACCUMULATOR.TIMESTAMP > TO_DATE('19-MAY-16 00:00:33', 'DD-MON-YY HH24:MI:SS')
AND ACTIVITY_ACCUMULATOR.TIMESTAMP < TO_DATE('20-MAY-16 00:00:33', 'DD-MON-YY HH24:MI:SS')
--AND USERS.BATCH_UID IN ('Sample_00000')
AND USERS.USER_ID='sample.userid'
--AND CM.BATCH_UID IN ('ACourse_00000')
ORDER BY TIMESTAMP ASC
;
