/*Oracle. Course/user management at a glance - Describes attributes of recently-modified enrollment DSK RS2016 */

SELECT 
  'The Enrollment DSK <b>'||TERM_ENROLLMENT_DSK||'</b><ul><li> Was modified on '||TERM_ENROLLMENTS_MODIFIED||'.</li><li>'||ENABLED_COUNT||' enrollments are ENABLED/AVAILABLE in the DSK.</li><li>'||DISABLED_COUNT||' enrollments are DISABLED in the DSK.</li><li>'||UNAVAILABLE_COUNT||' enrollments are UNAVAILABLE in the DSK.</li></ul><br>' AS MESSAGE
FROM
(SELECT 
  DS.DTMODIFIED AS TERM_ENROLLMENTS_MODIFIED
  ,DS.BATCH_UID AS TERM_ENROLLMENT_DSK
/*  ,CASE 
      WHEN cu.row_status=0 THEN 'ENABLED'
      ELSE 'DISABLED/OTHER'
   END EnrollStatus
  ,CASE
    WHEN CU.AVAILABLE_IND='Y' THEN 'AVAILABLE'
    ELSE 'UNAVAILABLE'
   END ENROLL_AVAILABILITY*/
--  ,COUNT(CU.PK1) AS ENROLLMENT_COUNT_PER_STATUS
  ,COUNT(CASE WHEN (CU.ROW_STATUS=0 AND CU.AVAILABLE_IND='Y') THEN 1 END) AS ENABLED_COUNT
  ,COUNT(CASE WHEN CU.ROW_STATUS=2 THEN 1 END) AS DISABLED_COUNT
--  ,COUNT(CASE WHEN CU.AVAILABLE_IND='Y' THEN 1 END) AS AVAILABLE_COUNT
  ,COUNT(CASE WHEN CU.AVAILABLE_IND='N' THEN 1 END) AS UNAVAILABLE_COUNT
FROM bblearn.data_source DS
INNER JOIN bblearn.COURSE_USERS CU
  ON DS.PK1=CU.DATA_SRC_PK1
WHERE DS.DTMODIFIED > sysdate-30 
AND DS.BATCH_UID LIKE 'ENR_%'
GROUP BY DS.DTMODIFIED, DS.BATCH_UID, CU.ROW_STATUS,CU.AVAILABLE_IND
ORDER BY DS.DTMODIFIED DESC, DS.BATCH_UID, CU.ROW_STATUS,CU.AVAILABLE_IND ASC)
;

/*
SELECT * FROM BBLEARN.COURSE_USERS;

SELECT 
  DTMODIFIED AS TERM_COURSES_MODIFIED
  ,BATCH_UID AS TERM_COURSES_DSK
FROM bblearn.data_source
WHERE DTMODIFIED > sysdate-30 
AND BATCH_UID LIKE 'ENR_%'
ORDER BY DTMODIFIED DESC;
*/